apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.APP_NAME }}"
  labels:
    app: "{{ .Values.APP_NAME }}"

spec:
  ports:
    - protocol: TCP
      port: {{ .Values.app.listen.port}}
      targetPort: {{ .Values.app.listen.port}}
  selector:
    app: "{{ .Values.APP_NAME }}"