APP_NAME: "black-book-frontend"
APP_IMAGE_NAME: "harbor.itm-space.net/front/blackbook-black-book-frontend-develop"
APP_IMAGE_TAG: "latest"
VITE_BASE_URL: "http://keycloak.it-mentor.space/"
INGRESS_HOST: "black-book-frontend-develop.it-mentor.space"

replicaCount: 1

app:
  listen:
    port: 3000

resources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "500m"

